name: south_cinema
description: Cinema app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Value equality
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1
  # Local cache
  shared_preferences: ^2.0.18
  # Network
  internet_connection_checker: ^1.0.0+1
  # Firebase
  firebase_core: ^2.7.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
