name: south_cinema
description: Cinema app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.1.2
  # Value equality
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1
  # Local cache
  shared_preferences: ^2.0.18
  # Network
  internet_connection_checker: ^1.0.0+1
  # Firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.4
  firebase_auth_mocks: ^0.10.3
  fake_cloud_firestore: ^2.4.0
  # Date formatting
  intl: ^0.17.0
  # Youtube video player
  youtube_player_flutter: ^8.1.2
  # iOS icons
  cupertino_icons: ^1.0.2
  # Navigation
  go_router: ^6.5.7
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  build_runner: ^2.3.3

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

assets:
  fonts:
    - family: DMSans
      fonts:
        - assets: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - assets: assets/fonts/DMSans-BoldItalic.ttf
          style: italic
          weight: 700
        - assets: assets/fonts/DMSans-Italic.ttf
          style: italic
        - assets: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - assets: assets/fonts/DMSans-MediumItalic.ttf
          style: italic
          weight: 500
        - assets: assets/fonts/DMSans-Regular.ttf
          weight: 400