// Mocks generated by Mockito 5.4.0 from annotations
// in south_cinema/test/features/reservations/presentation/bloc/user_reservations_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:south_cinema/core/error/error.dart' as _i6;
import 'package:south_cinema/features/reservations/domain/entities/reservation.dart'
    as _i7;
import 'package:south_cinema/features/reservations/domain/repositories/reservations_repository.dart'
    as _i2;
import 'package:south_cinema/features/reservations/domain/usecases/get_user_reservations.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeReservationsRepository_0 extends _i1.SmartFake
    implements _i2.ReservationsRepository {
  _FakeReservationsRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [GetUserReservations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserReservations extends _i1.Mock
    implements _i4.GetUserReservations {
  MockGetUserReservations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ReservationsRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeReservationsRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.ReservationsRepository);
  @override
  _i5.Future<_i3.Either<_i6.BaseError, List<_i7.Reservation>>> call(
          {required String? uid}) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
          {#uid: uid},
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.BaseError, List<_i7.Reservation>>>.value(
                _FakeEither_1<_i6.BaseError, List<_i7.Reservation>>(
          this,
          Invocation.method(
            #call,
            [],
            {#uid: uid},
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.BaseError, List<_i7.Reservation>>>);
}
